### ISSUE TITLE
YT is not ready on page refresh

### ISSUE THREAD

**Issue by olemarius** [NomNes/vue3-youtube#1]
![image](https://user-images.githubusercontent.com/184536/108237728-7b96da80-7148-11eb-959d-cfb48a1e5a69.png)

I get an error that YT is not ready after refreshing the page, using the local example provided here https://github.com/NomNes/vue3-youtube 

The workaround was to delay it with a setTimeout.. 
```
        mounted(){
            let self = this;
            setTimeout(() => {
                self.showVideo = true;
            }, 500)
        },
```

The issue occurs both when adding the component globally and locally.

**Comment by NomNes** [comment]
@olemarius Thank you for your feedback, I will study it soon!

**Comment by NomNes** [comment]
@olemarius could you give me an example to reproduce?

**Comment by olemarius** [comment]
Yep, I can create a reproducable repo as soon as I get time.

If you don't want to wait, go here https://vitejs.dev/guide/#scaffolding-your-first-vite-project and scaffold a new Vue 3 Typescript project, then add the youtube component

**Comment by olemarius** [comment]
Update: I've set up a clean repo but it didn't reproduce the issue. Will spend some more time trying to reproduce and give you an update.

**Comment by olemarius** [comment]
This is strange, I'm now no longer able to reproduce the issue. No changes made, so I'll close the issue and reopen again if it returns.

**Comment by 1Map** [comment]
@NomNes 

After so many years this bug is still there.

In my case I have 2 viewers/players on a page.  The first gives the error as shown above and the second not (More like a race condition).

Reason for that is:

`InitPlayer` is getting fired on both players (which is correct), but, on the first player,

`window.onYouTubeIframeAPIReady = function() {`

did not have time to fire, so `InitPlayer` then gives an error on YT not defined.  This error only shows for the first player.  By the time the second player do a `InitPlayer`, `onYouTubeIframeAPIReady` had time to fire, so YT is no longer undefined.
